### ISSUE TITLE
`from_concept_to_math.ipynb` missing `delta y` in section 2.5

### ISSUE THREAD

**Issue by erexer** [landlab/csdms_2022_landlab_clinics#3]
For section 2.5 in  [`from_concept_to_math.ipynb`](https://github.com/landlab/csdms_2022_landlab_clinics/blob/main/part1_art_of_modeling/notebooks/from_concept_to_math.ipynb)  under "(click to see solution)" and "Pull out constants", the right side of the equation should be `$$ \rho_s U \Delta x \Delta y + \rho_s \Delta y q(x) - \rho_s \Delta y q(x+\Delta x)$$`.

**Comment by gregtucker** [comment]
Good catch, thanks @erexer! Now fixed.
